### ISSUE TITLE
Regarding the GCN results of table 5 in the paper

### ISSUE THREAD

**Issue by aks1207** [MaoXinn/RREA#3]
Hi, its a great paper, got a lot of insights from it. 
I would like to know the configurations or the setting you used to report GCN results in Table 5 of the paper particularly the loss function and whether the initial random embeddings are trainable or not and have you used the relation information in the loss function.
And can you elaborate more on unit W in table 4 (Is it minimizing || w-I ||2 )?

**Comment by MaoXinn** [comment]
The reported GCN results also use Equation (19) as the loss function, all the embeddings are randomly initialized and trainable.
GCN in Table 5 does not use relational information, just vanilla GCN.

For Table 4, unit W means the W is a unit matrix, i.e., not using transformation.
Minimizing || w-I ||^2_2 (i.e. equation 8) is used by the Orth. methods.

Thanks for you attention ~

**Comment by aks1207** [comment]
hi ,
so unit W means there is not weight matrix at all , so is it aggregation without any weights?
And why do you think the initial random embeddings should be trainable won't it make things too easy for the network to decrease the loss?

**Comment by MaoXinn** [comment]
Yes, there is no transformation matrix at all.
The initial random embeddings must be trainable. 
For your concern, I don't believe it's a bad thing that the loss is easy to decrease.
You can look at my latest paper Dual-AMN, in which EA models converge dozens of times faster, but performance is further improved.

**Comment by aks1207** [comment]
will look into it and can you share the GCN experiment code of Table 5 if it is not too much of work .

Thanks a lot for the quick replies.

**Comment by MaoXinn** [comment]
Sorry, we didn't save the code of this experiment specifically ┓( ´∀` )┏.
Maybe you can modify the code of GCN-align (https://github.com/1049451037/GCN-Align).

**Comment by aks1207** [comment]
ok , thanks
