### ISSUE TITLE
公式和代码对应不上

### ISSUE THREAD

**Issue by xue19890510** [MaoXinn/RREA#6]
你好 我看layer.py有这么两行代码：
                bias = tf.reduce_sum(neighs * rels_sum, 1, keepdims=True) * rels_sum
                neighs = neighs - 2 * bias
这个应该对应论文Relational Reflection Aggregate Layer: 
M_{r_k}h_{e_j} 
为啥看起来是h_{e_j}在左边，是左乘啊，但是公式是h_{e_j} 在右边，是右乘，这个能解释下么，万分感谢

**Comment by MaoXinn** [comment]
因为前两个向量的内积出来的是一个标量，我为了计算方便用逐元素乘法和求和代替了。
逐元素乘法可以交换，所以左右无所谓的。

--------------原始邮件--------------
发件人："xue19890510 ***@***.***&gt;;
发送时间：2023年4月15日(星期六) 晚上6:21
收件人："MaoXinn/RREA" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[MaoXinn/RREA] 公式和代码对应不上 (Issue #6)
-----------------------------------

 

 
你好 我看layer.py有这么两行代码：
 bias = tf.reduce_sum(neighs * rels_sum, 1, keepdims=True) * rels_sum
 neighs = neighs - 2 * bias
 这个应该对应论文Relational Reflection Aggregate Layer:
 M_{r_k}h_{e_j}
 为啥看起来是h_{e_j}在左边，是左乘啊，但是公式是h_{e_j} 在右边，是右乘，这个能解释下么，万分感谢
